### ISSUE TITLE
(Frontend) Create a "Save to Favorites" button for each topic in the category page

### ISSUE THREAD

**Issue by tu2463** [CMU-313/nodebb-f24-sweethearts#31]
In the category page, add an unfilled star button to the left of each topic.
Clicking on the star button will turn it into a filled star
![Image](https://github.com/user-attachments/assets/eb713cfe-e403-4c3e-8f76-ab5386caed78)

**Comment by alicekang1** [comment]
Finished issue, but in front end repository.

Pull Request title: Created a Favorites Button for each Topic in Discussions page #9
Pull Request link: https://github.com/CMU-313/nodebb-frontend-f24-sweethearts/pull/9
